// Generated by CIRCT unknown git version

// ----- 8< ----- FILE "LayerC.sv" ----- 8< -----

// Generated by CIRCT unknown git version
module layer_c(	// /home/htamas/git/tt10-py-checkers/src/layer_c/layer_c.py:7
  input  [9:0] pix_x,
               pix_y,
               counter,
  input  [7:0] switches,
  input  [5:0] below,
  input        test,
  output [5:0] above
);

  wire [6:0] _GEN = pix_x[6:0] + {counter[4:0], 2'h0};	// /home/htamas/git/tt10-py-checkers/src/layer_c/layer_c.py:19
  wire [9:0] _GEN_0 = counter / 10'h2;	// /home/htamas/git/tt10-py-checkers/src/layer_c/layer_c.py:20
  wire [6:0] _GEN_1 = pix_y[6:0] + _GEN_0[6:0];	// /home/htamas/git/tt10-py-checkers/src/layer_c/layer_c.py:20
  assign above =
    _GEN[6] ^ _GEN_1[6]
      ? {switches[2], switches[7], switches[1], switches[7], switches[0], switches[7]}
      : below;	// /home/htamas/git/tt10-py-checkers/src/layer_c/layer_c.py:17, :19, :20, :21, :22, :23, :24, :25, :29
endmodule


// ----- 8< ----- FILE "LayerC.tcl" ----- 8< -----


