`default_nettype none

module feedback (
    input wire ogfeedback, // < xor feedback
    input wire excitedpulse, // < 1
    input wire inhibitorysignal, // < 0
    output wire feedbackselected //mod signal that gets passed into lfsr 
);

//reg [0:0] feedbackselected_r;
// takes og feedback generated by lfsr and allows the synapses to modify it 
// 
assign feedbackselected = (ogfeedback | excitedpulse) & ~inhibitorysignal;

//assign feedbackselected = feedbackselected_r;


//if both synapses are inactive (no excitation or inhibition), selected_feedback will just equal original_feedback, maintaining the LFSR’s usual behavior.
//if excitatory pulse is active, it will make the feedback more likely to be 1, pushing the LFSR to toggle its state more actively.
//if inhibitory signal is active, it will force the feedback to 0, which suppresses the feedback and dampens the LFSR's toggle.

endmodule
