/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 14.2.1 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:4" *)
(* generator = "Amaranth" *)
module layer_a(pix_y, counter, switches, below, above, pix_x);
  reg \$auto$verilog_backend.cc:2348:dump_module$1  = 0;
  wire [14:0] \$1 ;
  wire [15:0] \$2 ;
  wire [11:0] \$3 ;
  wire [12:0] \$4 ;
  wire \$5 ;
  wire \$6 ;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:14" *)
  output [5:0] above;
  reg [5:0] above;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:11" *)
  input [5:0] below;
  wire [5:0] below;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:9" *)
  input [9:0] counter;
  wire [9:0] counter;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:20" *)
  wire [5:0] layer_color;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:19" *)
  wire layer_sel;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:17" *)
  wire [9:0] layer_x;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:18" *)
  wire [9:0] layer_y;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:7" *)
  input [9:0] pix_x;
  wire [9:0] pix_x;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:8" *)
  input [9:0] pix_y;
  wire [9:0] pix_y;
  (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:10" *)
  input [7:0] switches;
  wire [7:0] switches;
  assign \$4  = pix_y + (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:25" *) \$3 ;
  assign \$5  = \$2 [8] ^ (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:26" *) \$4 [8];
  assign \$6  = pix_y[1] ^ (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:26" *) pix_x[0];
  assign layer_sel = \$5  & (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:26" *) \$6 ;
  assign \$1  = counter * (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:24" *) 5'h10;
  assign \$2  = pix_x + (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:24" *) \$1 ;
  assign \$3  = counter * (* src = "/home/htamas/git/tt10-py-checkers/src/layer_a/layer_a.py:25" *) 2'h2;
  always @* begin
    if (\$auto$verilog_backend.cc:2348:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (layer_sel) begin
      above = { switches[6], switches[2], switches[6], switches[1], switches[6], switches[0] };
    end else begin
      above = below;
    end
  end
  assign layer_x = \$2 [9:0];
  assign layer_y = \$4 [9:0];
  assign layer_color = { switches[6], switches[2], switches[6], switches[1], switches[6], switches[0] };
endmodule
