// File: layer_b.v
// Generated by MyHDL 0.11.51
// Date:    Mon Mar 10 03:00:59 2025 UTC


`timescale 1ns/10ps

module layer_b (
    pix_x,
    pix_y,
    counter,
    switches,
    below,
    above
);


input [9:0] pix_x;
input [9:0] pix_y;
input [9:0] counter;
input [7:0] switches;
input [5:0] below;
output [5:0] above;
reg [5:0] above;

reg [5:0] layer_color;
reg layer_sel;
reg [9:0] layer_x;
reg [9:0] layer_y;



always @(layer_x, layer_sel, pix_x, switches, layer_y, counter, pix_y, below, layer_color) begin: func
    layer_x = (pix_x + (counter * 7));
    layer_y = ((pix_y + counter) + (counter / 2));
    layer_sel = ((layer_x[7] ^ layer_y[7]) & ((~pix_y[0]) ^ pix_x[1]));
    layer_color = {switches[5], (!switches[2]), switches[4], (!switches[1]), switches[3], (!switches[0])};
    if (layer_sel) begin
        above = layer_color;
    end
    else begin
        above = below;
    end
end

endmodule
