if(NOT icestorm_FOUND)
    if(NOT DEFINED ICEPACK_PATH)
        find_program(ICEPACK_PATH NAMES icepack)
        if(${ICEPACK_PATH} STREQUAL "ICEPACK_PATH-NOTFOUND")
            unset(ICEPACK_PATH)
        endif()
    endif()
    if(DEFINED ICEPACK_PATH)
        message(STATUS "icepack path: ${ICEPACK_PATH}")
    else()
        message(STATUS "icepack path: **MISSING**")
    endif()

    if(NOT DEFINED ICEPROG_PATH)
        find_program(ICEPROG_PATH NAMES iceprog)
        if(${ICEPROG_PATH} STREQUAL "ICEPROG_PATH-NOTFOUND")
            unset(ICEPROG_PATH)
        endif()
    endif()
    if(DEFINED ICEPROG_PATH)
        message(STATUS "iceprog path: ${ICEPROG_PATH}")
    else()
        message(STATUS "iceprog path: **MISSING**")
    endif()

    if(NOT DEFINED ICEPLL_PATH)
        find_program(ICEPLL_PATH NAMES icepll)
        if(${ICEPLL_PATH} STREQUAL "ICEPLL_PATH-NOTFOUND")
            unset(ICEPLL_PATH)
        endif()
    endif()
    if(DEFINED ICEPLL_PATH)
        message(STATUS "icepll path: ${ICEPLL_PATH}")
    else()
        message(STATUS "icepll path: **MISSING**")
    endif()

    if(NOT DEFINED ICETIME_PATH)
        find_program(ICETIME_PATH NAMES icetime)
        if(${ICETIME_PATH} STREQUAL "ICETIME_PATH-NOTFOUND")
            unset(ICETIME_PATH)
        endif()
    endif()
    if(DEFINED ICETIME_PATH)
        message(STATUS "icetime path: ${ICETIME_PATH}")
    else()
        message(STATUS "icetime path: **MISSING**")
    endif()

    if(DEFINED ICEPACK_PATH AND DEFINED ICEPROG_PATH AND DEFINED ICEPLL_PATH AND DEFINED ICETIME_PATH)
        set(icestorm_FOUND ON)
    endif()
endif()